### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by connorjoleary** [connorjoleary/DeepCite#95]
**Describe the bug**
The reddit post https://www.reddit.com/r/todayilearned/comments/np87ef/til_of_the_golden_spruce_a_gorgeous_one_of_a_kind/
gives this error
```
Traceback (most recent call last): File "/app/main.py", line 28, in deep_cite tree = Tree(link, claim) File "/app/tree.py", line 24, in __init__ self.tree_root = Claim(url, claim) File "/app/claim.py", line 57, in __init__ self.parse_child() File "/app/claim.py", line 266, in parse_child self.create_children(ref2text, scores) File "/app/claim.py", line 146, in create_children self.child.append(Claim(ref2text[words], words, scores[i], (self.height +1), self)) # does ref2text allow for multiple links File "/app/claim.py", line 57, in __init__ self.parse_child() File "/app/claim.py", line 266, in parse_child self.create_children(ref2text, scores) File "/app/claim.py", line 165, in create_children self.child.append(Claim(ref2text[ref_key], words, scores[i], (self.height +1), self)) File "/app/claim.py", line 57, in __init__ self.parse_child() File "/app/claim.py", line 187, in parse_child citation = wiki(self.href, self.parent.href) File "/app/wiki_scraper.py", line 26, in wiki target_link = links[linkdict[link] + 1] IndexError: list index out of range
```

**Comment by connorjoleary** [comment]
Fixed through recent mr
